name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2
        
        
      - name: login to dockerhub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{secrets.DOCKERHUB_NAME }}
          password: ${{secrets.DOCKERHUB_KEY }}
          
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.2.2
        with:
          push: true
          tags: anasrafa/repo1:goapi2
      
  
