name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Hub Sign-in
        run: docker login -u ${{secrets.DOCKERHUB_NAME }} -p ${{ secrets.DOCKERHUB_KEY}}
      - name: Building Docker Image
        run: docker build -t anasrafa/repo1:goApiv2 -t anasrafa/repo1:${GITHUB_RUN_ID} .
      - name: Publish Docker Image
        run: docker push anasrafa/repo1
      
    
    
      
  
